package com.rcompany.tablecreater.dtos.column;

import lombok.*;

@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class ColumnCreateDto {
    private String columnName;
    private String columnTypeDto;
    private Boolean autoGenerated;
}
